import type { AuditResult, AuditUser, AuditFlag } from '../types.js'

const RULE_LABELS: Record<string, string> = {
  SUPER_PRIVILEGE: 'SUPER Privilege',
  ALL_PRIVILEGES_GLOBAL: 'ALL PRIVILEGES on *.*',
  GRANT_OPTION_GLOBAL: 'GRANT OPTION on *.*',
  FILE_PRIVILEGE: 'FILE Privilege',
  DANGEROUS_INFRA_PRIV: 'Dangerous Infra Privilege',
  WILDCARD_HOST: 'Wildcard Host (%)',
  PASSWORD_EXPIRED: 'Password Expired',
  ALL_PRIVILEGES_SCHEMA: 'ALL PRIVILEGES on Schema',
  USER_MANAGEMENT_PRIV: 'User Management Privilege',
  NO_PASSWORD_LIFETIME: 'No Password Expiry Policy',
  WILDCARD_HOST_SELECT_ONLY: 'Wildcard Host (SELECT only)',
  DUPLICATE_USERNAME: 'Duplicate Username',
}

const SEVERITY_ICON: Record<string, string> = {
  HIGH: '[HIGH]',
  MEDIUM: '[MEDIUM]',
  LOW: '[LOW]',
  CLEAN: '[CLEAN]',
}

function formatDate(iso: string): string {
  return new Date(iso).toUTCString()
}

function flagRow(flag: AuditFlag): string {
  const label = RULE_LABELS[flag.rule] ?? flag.rule
  return `  - **${flag.severity}** — ${label}: ${flag.detail}`
}

function userSection(u: AuditUser): string {
  const statusParts: string[] = []
  if (u.accountLocked) statusParts.push('LOCKED')
  if (u.passwordExpired) statusParts.push('PASSWORD EXPIRED')
  if (statusParts.length === 0) statusParts.push('Active')
  const status = statusParts.join(', ')

  const lines: string[] = [
    `### ${u.user}@${u.host}`,
    '',
    `| Field | Value |`,
    `|-------|-------|`,
    `| **Risk Level** | ${SEVERITY_ICON[u.riskLevel] ?? ''} ${u.riskLevel} |`,
    `| **Auth Plugin** | ${u.plugin} |`,
    `| **Status** | ${status} |`,
    `| **Password Lifetime** | ${u.passwordLifetime !== null ? `${u.passwordLifetime} days` : 'NULL (no rotation)'} |`,
    `| **Flags** | ${u.flags.length} |`,
    '',
  ]

  if (u.flags.length > 0) {
    lines.push('**Flags:**')
    lines.push('')
    for (const flag of u.flags) {
      lines.push(flagRow(flag))
    }
    lines.push('')
  }

  if (u.grants.length > 0) {
    lines.push('**SHOW GRANTS:**')
    lines.push('')
    lines.push('```sql')
    for (const grant of u.grants) {
      lines.push(grant + ';')
    }
    lines.push('```')
    lines.push('')
  }

  return lines.join('\n')
}

export function generateMarkdownReport(result: AuditResult): string {
  const { instance, auditedAt, summary, users } = result

  const high = users.filter(u => u.riskLevel === 'HIGH')
  const medium = users.filter(u => u.riskLevel === 'MEDIUM')
  const low = users.filter(u => u.riskLevel === 'LOW')
  const clean = users.filter(u => u.riskLevel === 'CLEAN')

  const lines: string[] = [
    `# Rogue DB User Audit Report`,
    '',
    `| Field | Value |`,
    `|-------|-------|`,
    `| **Instance** | ${instance} |`,
    `| **Audited At** | ${formatDate(auditedAt)} |`,
    `| **Total Users** | ${summary.totalUsers} |`,
    `| **System Users (excluded)** | ${summary.systemUsers} |`,
    '',
    '## Summary',
    '',
    `| Risk Level | Count |`,
    `|------------|-------|`,
    `| HIGH | ${summary.highRisk} |`,
    `| MEDIUM | ${summary.mediumRisk} |`,
    `| LOW | ${summary.lowRisk} |`,
    `| CLEAN | ${summary.clean} |`,
    '',
  ]

  if (high.length > 0) {
    lines.push('## High Risk Users')
    lines.push('')
    for (const u of high) lines.push(userSection(u))
  }

  if (medium.length > 0) {
    lines.push('## Medium Risk Users')
    lines.push('')
    for (const u of medium) lines.push(userSection(u))
  }

  if (low.length > 0) {
    lines.push('## Low Risk Users')
    lines.push('')
    for (const u of low) lines.push(userSection(u))
  }

  if (clean.length > 0) {
    lines.push('## Clean Users')
    lines.push('')
    for (const u of clean) lines.push(userSection(u))
  }

  lines.push('---')
  lines.push('')
  lines.push(`*Report generated by Rogue User Watchdog on ${formatDate(auditedAt)}*`)

  return lines.join('\n')
}
