import { ComparisonResult } from '../differ/types.js';
import { generateAlterTable } from './table-generator.js';
import { generateDropCreate } from './drop-create-generator.js';
import { generateIndexChanges } from './index-generator.js';
import { writeSingleFile, writeIndividualFiles } from './output-writer.js';
import { GenerationOutput } from './types.js';

export function generatePreview(result: ComparisonResult): string {
  if (result.status === 'unchanged') return '-- No changes';

  const statements: string[] = [];

  if (result.objectType === 'tables') {
    if (result.status === 'added' && result.targetRaw) {
      statements.push(result.targetRaw.trim().replace(/;?\s*$/, ';'));
    } else if (result.status === 'removed') {
      statements.push(`DROP TABLE IF EXISTS \`${result.name}\`;`);
    } else if (result.status === 'modified') {
      statements.push(...generateAlterTable(result));
    }
  } else if (result.objectType === 'indexes') {
    const { drop, create } = generateIndexChanges(result);
    statements.push(...drop, ...create);
  } else {
    const { drop, create } = generateDropCreate(result);
    statements.push(...drop, ...create);
  }

  return statements.length > 0 ? statements.join('\n\n') : '-- No migration statements';
}

export async function generateMigration(
  results: ComparisonResult[],
  outputPath: string,
  singleFile: boolean
): Promise<GenerationOutput> {
  const changed = results.filter((r) => r.status !== 'unchanged');

  // Collect all statements in the correct order per the plan:
  // 1. DROP TRIGGER/EVENT/VIEW/PROCEDURE/FUNCTION
  // 2. DROP TABLE (removed tables)
  // 3. CREATE TABLE (added tables)
  // 4. ALTER TABLE (modified tables)
  // 5. CREATE/DROP INDEX (standalone index changes)
  // 6. CREATE VIEW/PROCEDURE/FUNCTION/TRIGGER/EVENT

  const dropStatements: string[] = [];
  const dropTableStatements: string[] = [];
  const createTableStatements: string[] = [];
  const alterTableStatements: string[] = [];
  const indexDropStatements: string[] = [];
  const indexCreateStatements: string[] = [];
  const createStatements: string[] = [];

  const dropOrder = ['triggers', 'events', 'views', 'procedures', 'functions'];

  for (const objectType of dropOrder) {
    const items = changed.filter(
      (r) => r.objectType === objectType && (r.status === 'removed' || r.status === 'modified')
    );
    for (const item of items) {
      const { drop } = generateDropCreate(item);
      dropStatements.push(...drop);
    }
  }

  // Removed tables
  for (const item of changed.filter(
    (r) => r.objectType === 'tables' && r.status === 'removed'
  )) {
    dropTableStatements.push(`DROP TABLE IF EXISTS \`${item.name}\`;`);
  }

  // Added tables
  for (const item of changed.filter(
    (r) => r.objectType === 'tables' && r.status === 'added'
  )) {
    if (item.targetRaw) {
      createTableStatements.push(item.targetRaw.trim().replace(/;?\s*$/, ';'));
    }
  }

  // Modified tables
  for (const item of changed.filter(
    (r) => r.objectType === 'tables' && r.status === 'modified'
  )) {
    alterTableStatements.push(...generateAlterTable(item));
  }

  // Standalone index changes
  for (const item of changed.filter((r) => r.objectType === 'indexes')) {
    const { drop, create } = generateIndexChanges(item);
    indexDropStatements.push(...drop);
    indexCreateStatements.push(...create);
  }

  // Create views/procs/etc
  const createOrder = ['views', 'functions', 'procedures', 'triggers', 'events'];
  for (const objectType of createOrder) {
    const items = changed.filter(
      (r) => r.objectType === objectType && (r.status === 'added' || r.status === 'modified')
    );
    for (const item of items) {
      const { create } = generateDropCreate(item);
      createStatements.push(...create);
    }
  }

  const allStatements = [
    ...dropStatements,
    ...dropTableStatements,
    ...createTableStatements,
    ...alterTableStatements,
    ...indexDropStatements,
    ...indexCreateStatements,
    ...createStatements,
  ];

  if (singleFile) {
    const header = `-- Migration generated by RDS Schema Compare\n-- Generated at: ${new Date().toISOString()}\n\n`;
    const sql = header + allStatements.join('\n\n') + '\n';
    const filePath = await writeSingleFile(outputPath, sql);
    return { filesWritten: [filePath], totalStatements: allStatements.length, sql };
  } else {
    const files: { name: string; sql: string }[] = [];
    let idx = 1;
    for (const stmt of allStatements) {
      files.push({
        name: `${String(idx).padStart(4, '0')}.sql`,
        sql: stmt + '\n',
      });
      idx++;
    }
    const written = await writeIndividualFiles(outputPath, files);
    return { filesWritten: written, totalStatements: allStatements.length };
  }
}
